### ISSUE TITLE
Dev Task List for Updating Specs

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-project-management#46]
Per our discussion on 5/23/2022, this will be a running task list to update the specifications [located here](https://fecgov.github.io/fecfile-validate/) as we get clarification from FEC on how to build out the specs for FECFile Online. These specs will include requirements for validating the data users enter. 

**For every Transaction**
- [ ] FILER COMMITTEE ID NUMBER: Rule Reference should read "this is the ID of the Committee Account the report/transaction is associated with"
- [ ] "RECEIPT DESCRIPTION" should be renamed to "CONTRIBUTION PURPOSE DESCRIPTION". 
- [ ]  Rule reference for "TRANSACTION ID" should read "Must be unique for the life of a report (original + amendments) within each committee account. Letters, if included, must be uppercase."
- [ ] Fix COL SEQ numbers by subtracting 1 for those after TRANSACTION TYPE IDENTIFIER row

For specific transactions, please refer to [this Google spreadsheet](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1216228558). **Update: Each spec will be updated when the transaction form is built out in the application.**
- If a cell is in _yellow_, devs need to update the spec.
- if a cell is in _green_, devs have completed the update.
- if a cell is in _red_, BA still has an open question on the cell, do not update.

**Comment by AureliaKhorsand** [comment]
@mjtravers can we close this ticket? I don't think we're using it anymore, and we now update each schema within the transaction tickets themselves. If you agree, I can close this and mark as OBE.

**Comment by mjtravers** [comment]
> @mjtravers can we close this ticket? I don't think we're using it anymore, and we now update each schema within the transaction tickets themselves. If you agree, I can close this and mark as OBE.

Yes, this ticket is OBE and can be closed.
