### ISSUE TITLE
Updating Transaction wireframes

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#49]
### UX Tasks ### 
Here is the list of Transaction Wireframes to be completed:

#### Closed ####
- [x] Individual Receipt - Group A - fecfile-web-app#229
- [x] Offsets to Operating Expenditures - Group B - fecfile-web-app#230
- [x] Other Receipts - Group C - fecfile-web-app#231
- [x]  Tribal Receipt - Group D - fecfile-web-app#232
- [x] JF Transfers - Group E - fecfile-web-app#233
- [x] PAC JF Transfer Memo - Group F - fecfile-web-app#327

#### In Progress ####
- [x] Earmark Receipt - Group A - fecfile-web-app#459
- [x] Earmark Memo - Group G - fecfile-web-app#460

#### Awaiting Sprint Assignment ####
- [x] Individual Joint Fundraising Transfer Memo - Group A - fecfile-web-app#451
- [x] Tribal Joint Fundraising Transfer Memo - Group D - fecfile-web-app#448
- [x] Party Joint Fundraising Transfer Memo - Group F - fecfile-web-app#447
- [x] Transfer - Group F - fecfile-web-app#492

#### ADTR ####
- [x] PAC Earmark Receipt - Group F - fecfile-web-app#490
- [x] PAC Earmark Memo - Group G - fecfile-web-app#491

#### Awaiting Analysis ####
- [x] Individual Recount Receipt - Group A - fecfile-web-app#520
- [x] Party Recount Receipt - Group F - fecfile-web-app#529
- [x] PAC Recount Receipt - Group F - fecfile-web-app#530
- [x] Tribal Recount Receipt - Group D - fecfile-web-app#534
- [x] Individual Receipt - Non-Contribution Account - Group A - fecfile-web-app#519
- [x] Other Committee Receipt - Non-Contribution Account - Group F - fecfile-web-app#528
- [x] Business/Labor Organization Receipt - Non-Contribution Account - Group D - fecfile-web-app#533
- [x] Partnership Receipt -  Group D - fecfile-web-app#477
- [x] Partnership Memo - Group A - fecfile-web-app#478
- [x] Partnership Receipt Joint Fundraising Transfer Memo - Group D - fecfile-web-app#449
- [x] Partnership Individual Joint Fundraising Transfer Memo - Group A - fecfile-web-app#452

#### Product Backlog ####
- [x] Tribal National Party Convention Account - Group D - fecfile-web-app#537
- [x] Tribal National Party Headquarters Buildings Account - Group D - fecfile-web-app#536
- [x] Tribal National Party Recount Account - Group D - fecfile-web-app#535
- [x] Party National Party Headquarters Buildings Account - Group F - fecfile-web-app#531
- [x] PAC National Party Convention Account - Group F - fecfile-web-app#527
- [x] PAC National Party Headquarters Buildings Account - Group F - fecfile-web-app#526
- [x] PAC National Party Recount Account - Group F - fecfile-web-app#525
- [x]  Individual National Party Convention Account - Group A - fecfile-web-app#524
- [x] Individual National Party Headquarters Buildings Account - Group A - fecfile-web-app#523
- [x] Party National Party Recount Account - Group A - fecfile-web-app#522 
- [x] Individual National Party Recount Account - Group A - fecfile-web-app#521
- [x] Returned/Bounced Receipt - Group C - fecfile-web-app#512
- [x] PAC Returned/Bounced Receipt - Group F - fecfile-web-app#511
- [x] Partnership Individual Headquarters Account JF Transfer Memo - Group A - fecfile-web-app#507
- [ ] Partnership Individual Convention Account JF Transfer Memo - Group A - fecfile-web-app#506
- [x] Partnership Receipt Headquarters Account JF Transfer Memo - Group D - fecfile-web-app#505
- [ ] Partnership Receipt Convention Account JF Transfer Memo - Group D - fecfile-web-app#504
- [ ] Tribal National Party Convention Account JF Transfer Memo - Group D - fecfile-web-app#503
- [x] PAC National Party Headquarters Account JF Transfer Memo - Group F - fecfile-web-app#502
- [ ] PAC National Party Convention Account JF Transfer Memo - Group F - fecfile-web-app#501
- [x] Individual National Party Headquarters Account JF Transfer Memo - Group A - fecfile-web-app#500
- [ ] Individual National Party Convention Account JF Transfer Memo - Group A - fecfile-web-app#499
- [x] Joint Fundraising Transfer - National Party Headquarters Account - Group E- fecfile-web-app#498
- [ ] Joint Fundraising Transfer - National Party Convention Account - Group E - fecfile-web-app#497
- [ ] Unregistered Receipt - Group D - fecfile-web-app#488
- [ ] Party Returned/Bounced Receipt - Group F - fecfile-web-app#479
- [ ] Unregistered Receipt from Person - Returned/Bounced Receipt - Group D - fecfile-web-app#489
- [ ] Partnership Individual Recount Account JF Transfer Memo - Group A -  fecfile-web-app#469
- [ ] Partnership Receipt Recount Account JF Transfer Memo - Group D - fecfile-web-app#468
- [ ] Tribal National Party Recount Account JF Transfer Memo -  Group D - fecfile-web-app#466
- [ ] PAC National Party Recount Account JF Transfer Memo - Group F - fecfile-web-app#465
- [ ] Individual National Party Recount Account JF Transfer Memo - Group A - fecfile-web-app#464
- [ ] Joint Fundraising Transfer - National Party Recount Account - Group E - fecfile-web-app#463
- [ ] Refunds of Contributions to Unregistered Committees - Group D - fecfile-web-app#454
- [ ] Refunds of Contributions to Registered Committees - Group F - fecfile-web-app#453
- [ ] Earmark Receipt for Recount Account (Contribution) - Group A -  fecfile-web-app#513
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]
