### ISSUE TITLE
UX: Design Form 24 

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#75]
### Task
- [ ]  Create a new processing message
- [ ]  Create a new importing message
- [ ]  add backdoor code to submission of an amendment
- [ ]  tighten up the footer on are you sure 

### Select a Form 24
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmZmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb5d97c580f4b7d4ae9d7d00ff9c7e118ba39335/1102-%20Select%20form%2024.png)

### Select 24 Hour or 48 Hour
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjdmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5d74fecdabe26833778a1eb9a879c7e3f09bd59/1102-%20Select%20form%2024%20%E2%80%93%203.png)

### When amending a form 24
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzdmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51812dec1d6f3118dbef6e8087ac1af473c6768c/1102-%20Select%20form%2024%20%E2%80%93%20Amendments.png)

### Form 99 Report
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a754bdfc4a46e1ab9848acab7c34d42a8c2ab5f4/1400%20-%20Form%2099.png)

### Form 99 with dropdown
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkROQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adff0e2c70bffd63f847e997385a9b8f4bf1224a/1400%20-%20Form%2099%20-%20%20w%20dropdown.png)

### Would you like to compile a print preview?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ROQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1f4c9219e3eb54c6afdffdd105e0bfbb7d303e9/1103%20-%20Would%20you%20like%20to%20compile.png)

### Compiling
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56c87984353a481241f3d9c8cc70e264fcc80783/1103%20-%20Compiling%20your%20preview.png)

### Compiled
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cf16a9138d96099318fbf8803fab233e6a8b3a7/1103%20-%20PDF%20ompiled.png)

### Confirm innformation
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ZOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c219a2357dceec4786e07e879f3c22f0e6d30413/1339%20Confirm%20info.png)

### Submit Report
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWJmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1f0637deff0e94c4cb1f9bae73cad95e93caabd/1339%20submit%20report.png)

### Are you sure
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a28ef96c93e5ffbf983117b9453cb0ba03614161/1339%20submit%20report%20%E2%80%93%20Are%20you%20sure.png)
